version: "3.9"

services:
  java-server:
    build:
      context: ./server/omb-server
    container_name: omb_java_server
    ports:
      - "5000:5000"
    networks:
      - omb-net
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: omb_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:19
    container_name: omb_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - odoo_data:/var/lib/odoo
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}

volumes:
  postgres_data:
  odoo_data:

networks:
  omb-net:
    external: true
