<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKTvkenj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKTvkenj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKTvkenj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKTvkenj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKTvkenj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KTvkenj',
    'container.build_id' => 'bfd7da43',
    'container.build_time' => 1773145097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKTvkenj');
