<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK12lKxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK12lKxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK12lKxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK12lKxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK12lKxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K12lKxx',
    'container.build_id' => 'a5d3ba38',
    'container.build_time' => 1773230689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK12lKxx');
