<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgHmhFn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgHmhFn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgHmhFn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgHmhFn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNgHmhFn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NgHmhFn',
    'container.build_id' => 'adbd8bb4',
    'container.build_time' => 1773080019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgHmhFn');
