#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Modules
modules:
  path: /modules
  controller: App\Controller\ModuleController::modules
  methods: [ GET, POST, OPTIONS ]

module:
  path: /modules/{id}
  controller: App\Controller\ModuleController::module
  methods: [ GET, DELETE, PUT ]

module_full:
  path: /modules/{id}/full
  controller: App\Controller\ModuleController::module_full
  methods: [ GET ]

modules_user:
  path: /user/{user_id}/modules
  controller: App\Controller\ModuleController::modulesUser
  methods: [ GET ]

# Generación de módulos Odoo
generate_module:
  path: /api/generate-module
  controller: App\Controller\ModuleController::generateModule
  methods: [ POST, OPTIONS ]

# Models
models:
  path: /models
  controller: App\Controller\ModelController::models
  methods: [ GET, POST ]

model:
  path: /models/{id}
  controller: App\Controller\ModelController::model
  methods: [ GET, DELETE, PUT ]

models_module:
  path: /modules/{id}/models
  controller: App\Controller\ModelController::modelsModule
  methods: [ GET ]

# Fields
fields:
  path: /fields
  controller: App\Controller\FieldController::fields
  methods: [ GET, POST ]

field:
  path: /fields/{id}
  controller: App\Controller\FieldController::field
  methods: [ GET, DELETE, PUT ]

fields_model:
  path: /models/{id}/fields
  controller: App\Controller\FieldController::fieldsModel
  methods: [ GET ]

# Users
users:
  path: /users
  controller: App\Controller\UserController::users
  methods: [ GET, POST ]

user:
  path: /users/{id}
  controller: App\Controller\UserController::user
  methods: [ GET, DELETE, PUT ]

# Views
views:
  path: /views
  controller: App\Controller\ViewController::views
  methods: [ GET, POST ]

view:
  path: /views/{id}
  controller: App\Controller\ViewController::view
  methods: [ GET, DELETE, PUT ]

views_model:
  path: /models/{id}/views
  controller: App\Controller\ViewController::viewsModel
  methods: [ GET ]

# Views-fields
viewFields:
  path: /viewFields
  controller: App\Controller\ViewFieldController::viewFields
  methods: [ GET, POST ]

viewField:
  path: /viewFields/{id}
  controller: App\Controller\ViewFieldController::viewField
  methods: [ DELETE ]

# Deployments
deployments:
  path: /deployments
  controller: App\Controller\DeploymentController::deployments
  methods: [ GET, POST ]

deployment:
  path: /deployments/{id}
  controller: App\Controller\DeploymentController::deployment
  methods: [ GET, DELETE ]

# Login
login:
  path: /login
  controller: App\Controller\UserController::login
  methods: [ POST, OPTIONS ]