version: '3.8'

services:
  web:
    build: .
    container_name: omb-api
    volumes:
      - .:/var/www/html
      - ./provisioning/sites-enabled:/etc/apache2/sites-enabled
      - ../../odoo/addons:/mnt/extra-addons
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.webapp
    environment:
      ODOO_ADDONS_PATH: /mnt/extra-addons
      ODOO_HOST: omb_odoo
      ODOO_PORT: '8069'
      ODOO_DB: omb
      ODOO_USER: odoo
      ODOO_PASSWORD: odoo
    ports:
      - 8082:80
    networks:
      - omb-net
    tty: true
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: omb-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omb
      MYSQL_USER: odoo
      MYSQL_PASSWORD: odoo
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ../../docs/database:/docker-entrypoint-initdb.d:ro
    networks:
      - omb-net

networks:
  omb-net:
    external: true
