version: '3.8'

services:
  web:
    image: buig/sf-php8.0-apache
    container_name: omb-api
    volumes:
      - .:/code
      - ./provisioning/sites-enabled:/etc/apache2/sites-enabled
    env_file:
      - .env.webapp
    ports:
      - 8082:80
    networks:
      - omb-net
    tty: true

  db:
    image: mysql:8.0
    container_name: omb-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omb
      MYSQL_USER: odoo
      MYSQL_PASSWORD: odoo
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ../../docs/database:/docker-entrypoint-initdb.d:ro
    networks:
      - omb-net

networks:
  omb-net:
    driver: bridge
